services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.custom.address=:8000"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=arthur.maloron@proton.me"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--log.level=DEBUG"
    ports:
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
  
  
  angular-build:
    image: angular-build:latest
    container_name: angular-build
    volumes:
      - ./frontend/dist:/frontend/dist

  nginx-angular:
    image: custom-nginx:latest
    container_name: nginx-angular
    volumes:
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html
      - ./nginx/angular.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-angular.rule=Host(`manwhameter.com`)"
      - "traefik.http.routers.nginx-angular.entrypoints=websecure"
      - "traefik.http.routers.nginx-angular.tls=true"
      - "traefik.http.routers.nginx-angular.service=nginx-angular-service"
      - "traefik.http.services.nginx-angular-service.loadbalancer.server.port=443"
      - "traefik.http.routers.nginx-angular.tls.certresolver=myresolver"

  symfony:
    image: symfony-php:latest
    container_name: symfony
    volumes:
      - ./backend:/var/www/symfony

  nginx-symfony:
    image: custom-nginx:latest
    container_name: nginx-symfony
    volumes:
      - ./nginx/symfony.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/symfony
    depends_on:
      - symfony
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-symfony.rule=Host(`api.manwhameter.com`)"
      - "traefik.http.routers.nginx-symfony.entrypoints=websecure"
      - "traefik.http.routers.nginx-symfony.tls=true"
      - "traefik.http.routers.nginx-symfony.tls.certresolver=myresolver"
      - "traefik.http.services.nginx-symfony.loadbalancer.server.port=8000"
