framework:
    rate_limiter:
        anonymous_api:
            policy: 'sliding_window'
            limit: 500
            interval: '5 minute'
        login_route:
            policy: 'sliding_window'
            limit: 5
            interval: '5 minute'
        refresh_route:
            policy: 'sliding_window'
            limit: 10
            interval: '5 minute'
