framework:
    rate_limiter:
        anonymous_api:
            policy: 'sliding_window'
            limit: 1500
            interval: '15 minutes'
        authenticated_api:
            policy: 'sliding_window'
            limit: 1500
            interval: '15 minutes'